navikt/amt-deltaker

src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/Environment.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringService.kt, src/main/kotlin/no/nav/amt/deltaker/job/StatusUpdateJob.kt, src/main/kotlin/no/nav/amt/deltaker/job/leaderelection/LeaderElection.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepositoryTest.kt, src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt
Flytter jobb for å oppdatere status for deltakere til amt-deltaker.
=> jobb for å oppdatere deltakerstatus

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
https://trello.com/c/vFr3AULh/1380-ta-bort-datoer-p%C3%A5-ikke-aktuell
Dette med å oppdatere status ved forlengelse har visst blitt borte i oppsplittingen :)
=> fjerner datoer for ikke aktuell, endrer status ved forlengelse

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
Vi manglet noen tilfeller av oppdatering av status når man endret start- og/eller sluttdato, og det så litt rart ut i veilederflaten når f.eks. deltaker fortsatt står som deltar når startdato endres slik at den er i fremtiden.
=> skal oppdatere status når man endrer på datoer

src/main/kotlin/no/nav/amt/deltaker/amtperson/dto/NavBrukerDto.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/navbruker/NavBrukerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/navbruker/model/NavBruker.kt, src/main/kotlin/no/nav/amt/deltaker/navbruker/model/Oppfolgingsperiode.kt, src/main/resources/db/migration/V10__navbruker-add-columns.sql, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestRepository.kt
https://trello.com/c/hFeCoVht/1534-lese-inn-og-dele-oppf%C3%B8lgingsperiode-fra-dab
=> lagrer oppfølgingsperioder

src/main/kotlin/no/nav/amt/deltaker/deltaker/PameldingService.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt
https://trello.com/c/sGSXFheM/1515-veileder-f%C3%A5r-kun-melde-p%C3%A5-deltaker-p%C3%A5-tiltak-som-innbygger-har-tilgang-p%C3%A5-basert-p%C3%A5-innsatsgruppe
=> sjekker at bruker har riktig innsatsgruppe ved påmelding

src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerHistorikkService.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/HendelseService.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseDeltaker.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/VedtakServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt
https://trello.com/c/DcP2jSwQ/1571-endringsvedtaket-tekstendringer
Datoen man blir påmeldt skal vises i pdf-en for endringer
=> legger til første vedtak fattet på hendelser

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
https://trello.com/c/MgtHbpKY/1599-endre-oppstartdato-p%C3%A5-deltaker-med-status-har-sluttet
=> fikser bug ved endring av startdato

src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapper.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapperTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestRepository.kt
https://trello.com/c/arsTXh84/1600-sortering-av-deltakelser-p%C3%A5-oversikt-over-brukerens-tiltak-endre-det-vi-sender-til-valp
=> sorterer deltakelsene som sendes til tiltaksoversikten

src/main/kotlin/no/nav/amt/deltaker/application/plugins/Routing.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponse.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapper.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerEndringRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/internal/InternalApi.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapperTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerEndringRepositoryTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepositoryTest.kt, src/test/kotlin/no/nav/amt/deltaker/kafka/utils/Assertions.kt
https://trello.com/c/u3cb3MLw/1408-status-feilregistrert
=> støtte for å feilregistrere deltakere

src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapper.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerStatus.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapperTest.kt
https://trello.com/c/UIVUO58C/1388-legge-til-utdanning-som-en-%C3%A5rsak
=> legger til utdanning som sluttårsak

src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapper.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerStatus.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/Deltakerliste.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/kafka/DeltakerlisteConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringService.kt, src/test/kotlin/no/nav/amt/deltaker/deltakerliste/kafka/DeltakerlisteConsumerTest.kt, src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt
https://trello.com/c/nTtjDfmG/1391-avlyst-tiltaksgjennomf%C3%B8ring-hos-valp-p%C3%A5virker-deltakerstatus-og-%C3%A5rsak
=> legger til sluttårsak for avlyst gjennomføring, oppdaterer deltakere

src/main/kotlin/no/nav/amt/deltaker/deltaker/PameldingService.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/Deltakerliste.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt
https://trello.com/c/DMtYPbZj/1636-jeg-f%C3%A5r-meldt-p%C3%A5-nye-deltakere-p%C3%A5-gjennomf%C3%B8ringer-som-er-avbrutt
=> skal ikke kunne melde på avsluttet gjennomføring

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApi.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerEndring.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseType.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt
https://trello.com/c/UvbHudLB/1483-endre-deltakelse-n%C3%A5r-en-person-er-ikke-aktuell
=> legger til api og hendelse for reaktivering

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerEndring.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseType.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt
https://trello.com/c/1mRrBgMg/1659-legge-til-begrunnelse-for-forleng-deltakelse
=> tar med begrunnelse for forlengelse

src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV2Dto.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV2MapperService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Deltakelsesinnhold.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Deltaker.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Vedtak.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/db/VedtakRepositoryTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV2MapperServiceTest.kt
https://trello.com/c/yX4kHuGU/1669-endre-format-p%C3%A5-deltakervedvedtak-deltakerhistorikk
(kun endring i formatet)
=> endrer format på DeltakerVedVedtak

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerEndring.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseType.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt
https://trello.com/c/PK7x7y6c/1678-amt-deltaker-m%C3%A5-st%C3%B8tte-forslag-om-avslutning-av-deltakelse-og-ikke-aktuell
=> støtter forslag for avslutt deltakelse og ikke aktuell

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerEndring.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseType.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt
https://trello.com/c/SSsSaxMq/1682-legge-til-begrunnelse-for-reaktiver-deltakelse
=> tar i mot begrunnelse for reaktivering

src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/application/plugins/Routing.kt, src/main/kotlin/no/nav/amt/deltaker/internal/InternalApi.kt, src/test/kotlin/no/nav/amt/deltaker/ApplicationTest.kt, src/test/kotlin/no/nav/amt/deltaker/application/plugins/AuthenticationTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/PameldingApiTest.kt
https://trello.com/c/l2VDj8Fl/1765-relaste-deltakere-p%C3%A5-deltaker-v2
=> Endepunkt for å relaste deltaker på deltaker-v2

src/main/kotlin/no/nav/amt/deltaker/application/plugins/Authentication.kt
https://trello.com/c/KIcaMDJP/1727-obo-samarbeid-hendelser-p%C3%A5-tiltak-i-min-oversikt-og-enhetens-oversikt
=> Gi amt-distribusjon tilgang til api med systemkontekst

src/main/kotlin/no/nav/amt/deltaker/deltaker/PameldingService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV2Dto.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV2MapperService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Deltaker.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Kilde.kt, src/main/resources/db/migration/V19__deltaker_add_kilde.sql, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV2MapperServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestRepository.kt
https://trello.com/c/VQ21HtNC/1793-lagre-kilde-i-amt-deltaker
=> lagrer kilde

.github/workflows/deploy-unleash-apitoken.yaml, .nais/nais-dev.yaml, .nais/unleash-apitoken-dev.yaml, build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/unleash/UnleashToggle.kt
Co-authored-by: Line Moseng <line.moseng@nav.no>
Co-authored-by: Tia Firing <tia.firing@nav.no>
Co-authored-by: Marthe Frogner Holm <marthe.frogner.holm@nav.no>
https://trello.com/c/wajrKoff/1752-lese-inn-aft-arenadeltakere
=> Setter opp unleash klient

src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/Environment.kt, src/main/kotlin/no/nav/amt/deltaker/application/plugins/Routing.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/forslag/ForslagService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerProducerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV1Dto.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV1Producer.kt, src/main/kotlin/no/nav/amt/deltaker/internal/InternalApi.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumerTest.kt, src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/kafka/utils/Assertions.kt
https://trello.com/c/bMUTnyE1/1815-amt-deltaker-skal-produsere-aft-deltakere-til-deltaker-v1-ved-lansering
=> publiserer til deltaker-v1 hvis vi er master

src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/internal/InternalApi.kt
https://trello.com/c/ZNVOu5aM/1826-bug-innlesing-arenadeltakere-kommer-ikke-inn-p%C3%A5-deltakersiden-feilmelding
=> Aarsakmapping

src/main/kotlin/no/nav/amt/deltaker/hendelse/HendelseProducer.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/HendelseService.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseType.kt
https://trello.com/c/7c5RtOyM/1718-endringer-i-brevene-nye-titler-og-forslag-fra-ta
Endringen fra forslaget skal vises i pdf-en.
=> sender med endringen fra forslag som en del av hendelsen

src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapper.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerProducerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV1Dto.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerStatus.kt
https://trello.com/c/aWvFePdD/1756-eksponere-statustekst-p%C3%A5-deltakerv1-%C3%B8nske-fra-valp
=> Statusarsaktekst

src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapper.kt
…nger
https://trello.com/c/89vKWKO6/1958-oppdatere-hardkodede-navn-p%C3%A5-digiopparb
=> Tiltaksnavn

src/main/kotlin/no/nav/amt/deltaker/unleash/UnleashToggle.kt
https://trello.com/c/VtRl4j9E/1928-etter-lansering-legge-til-de-tre-nye-tiltakstypene-i-listen-over-tiltak-vi-alltid-er-master-for
=> komet er alltid master for oppfølging, arr og avklaring

src/main/kotlin/no/nav/amt/deltaker/unleash/UnleashToggle.kt
https://trello.com/c/v4xePS94/1929-etter-lansering-legge-til-de-to-neste-tiltakstypene-i-listen-over-tiltak-vi-kanskje-er-master-for
=> legger til nye tiltakstyper

src/main/kotlin/no/nav/amt/deltaker/deltaker/PameldingService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/Deltakerliste.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/DeltakerlisteRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/kafka/DeltakerlisteDto.kt, src/main/resources/db/migration/V29__deltakerliste_apent_for_pamelding.sql, src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestRepository.kt
https://trello.com/c/0LxxES6r/1965-skal-ikke-f%C3%A5-melde-p%C3%A5-tiltak-hvis-gjennomf%C3%B8ringen-er-stengt-for-p%C3%A5melding
=> Deltakerliste apentforpamelding

src/main/kotlin/no/nav/amt/deltaker/navbruker/NavBrukerService.kt
https://trello.com/c/VoyO1XgH/1878-fjerne-workaround-kode-fra-amt-deltaker-og-personservice
=> fjerner workaround for personer som mangler innsatsgruppe

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt
https://trello.com/c/FLDBGXzi/1972-det-publiseres-uendrede-deltakere-p%C3%A5-deltaker-v1-fra-amt-deltaker-som-f%C3%B8lge-av-oppdateringer-p%C3%A5-navbruker-topicen
=> må spesifisere hvilken parameter vi sender inn

src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorService.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorServiceTest.kt
https://trello.com/c/p0Zp9mZP/2009-legg-til-oppstartsdato-medf%C3%B8rer-ingen-endring-for-vta
=> må støtte at sluttdato er null

src/main/kotlin/no/nav/amt/deltaker/unleash/UnleashToggle.kt
https://trello.com/c/ewm6PMZr/2026-etter-lansering-legge-til-de-to-nye-tiltakstypene-i-listen-over-tiltak-vi-alltid-er-master-for
=> komet er alltid master for vasv og digiopparb

src/main/kotlin/no/nav/amt/deltaker/deltakerliste/Deltakerliste.kt
https://trello.com/c/XnIgh887/1987-fjerne-deltakerliste-status-planlagt-og-apentforinnsok
=> fjerner ubrukte deltakerlistestatuser

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/deltaker/forslag/kafka/ArrangorMeldingConsumer.kt
https://trello.com/c/vWhuVSEK/2059-amt-tiltaksarrangor-bff-m%C3%A5-dele-vurdering-fra-arrang%C3%B8r-p%C3%A5-topic
=> støtter vurdering fra arrangør

src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/unleash/UnleashToggle.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumerTest.kt
https://trello.com/c/tJEGBXqg/2084-lese-inn-kursdeltakere-i-verdikjeden
https://github.com/navikt/amt-tiltak/pull/912
=> Les arena deltakere og flytter håndtering av importertFraArena til amt-tiltak

build.gradle.kts
Reverts navikt/amt-deltaker#315
=> Revert "Bump kotlinVersion from 2.1.0 to 2.1.10"

src/main/kotlin/no/nav/amt/deltaker/internal/InternalApi.kt
https://trello.com/c/94dCO0nA/2095-akas-returnererte-ny-aktivitetskortid-for-person-som-allerede-har-aktivitetskort
=> Internal endepunkt for å relaste deltakere på deltakerId

src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/forslag/kafka/ArrangorMeldingConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/vurdering/VurderingService.kt
https://trello.com/c/4piTfysO/2159-flytte-vurderinger-til-amt-deltaker
=> Gjør klar lagring av vurderinger fra kafka som skal brukes når vi blir master for gruppeAMO

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseDeltaker.kt
https://trello.com/c/0m8P1j5M/2207-lage-brev-for-s%C3%B8kt-inn
=> Sender med ekstra data i hendelser som trengs i innsøkingsbrevet

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/application/plugins/Routing.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerHistorikkService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/PameldingService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApi.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/dto/DeltakerDto.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/dto/DeltakerDtoMapperService.kt, src/main/kotlin/no/nav/amt/deltaker/tiltakskoordinator/TiltakskoordinatorApi.kt, src/main/kotlin/no/nav/amt/deltaker/tiltakskoordinator/endring/EndringFraTiltakskoordinatorService.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerHistorikkServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/VedtakServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapperTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepositoryTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumerTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerDtoMapperServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringTest.kt, src/test/kotlin/no/nav/amt/deltaker/tiltakskoordinator/TiltakskoordinatorApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/tiltakskoordinator/endring/EndringFraTiltakskoordinatorServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestRepository.kt
https://trello.com/c/UtFz5diC/2224-tiltakskoordinator-kan-sette-p%C3%A5-venteliste
=> Venteliste

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt
Fikser feil rekkefølge på statements
=> Slette fra tabeller som har foreign key til deltaker

src/main/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApi.kt
=> Vise deltakelser på kurs i prod

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/deltaker/PameldingService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Deltaker.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseDeltaker.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt
https://trello.com/c/obk3jknq/2205-lage-brev-og-varsel-for-sett-p%C3%A5-venteliste
=> Legger til opprettet dato på hendelsedeltaker som skal brukes i brev

src/main/kotlin/no/nav/amt/deltaker/tiltakskoordinator/endring/EndringFraTiltakskoordinatorService.kt
https://trello.com/c/obk3jknq/2205-lage-brev-og-varsel-for-sett-p%C3%A5-venteliste
=> Ikke tillat at status settes til venteliste om den allerede er det for å unngå duplikater

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt, src/main/kotlin/no/nav/amt/deltaker/hendelse/HendelseService.kt, src/main/kotlin/no/nav/amt/deltaker/tiltakskoordinator/TiltakskoordinatorApi.kt, src/test/kotlin/no/nav/amt/deltaker/tiltakskoordinator/TiltakskoordinatorApiTest.kt
https://trello.com/c/XQ3FyK3T/2206-lage-brev-for-tildelt-plass
=> Deler hendelse for tildel plass

src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerHistorikkService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/vurdering/VurderingService.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerHistorikkServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/VedtakServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapperTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumerTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerDtoMapperServiceTest.kt, src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/data/TestRepository.kt
https://trello.com/c/Gt88uGdE/2270-vurderinger-havner-ikke-lengre-i-historikken
=> Viser vurderinger i historikken også når vi er master

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/Environment.kt, src/test/kotlin/no/nav/amt/deltaker/deltakerliste/tiltakstype/kafka/TiltakstypeConsumerTest.kt
Venter med å oppdatere amt-lib til `SettPaaVenteliste` er ferdig implementert
=> Gjør klar til migrering til tiltakstyper-v3

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandler.kt
https://trello.com/c/dmPgsl3w/2163-tiltaksarrang%C3%B8r-avslutte-deltakelse-modal-skal-man-angi-om-kurset-er-fullf%C3%B8rt-eller-ikke
=> Fikser feil som gjør at man får avbrutt status for tidlig

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/Application.kt, src/main/kotlin/no/nav/amt/deltaker/arrangor/ArrangorConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/forslag/kafka/ArrangorMeldingConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/kafka/DeltakerlisteConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/deltakerliste/tiltakstype/kafka/TiltakstypeConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/navansatt/NavAnsattConsumer.kt, src/main/kotlin/no/nav/amt/deltaker/navbruker/NavBrukerConsumer.kt
https://trello.com/c/3fiag15H/2355-h%C3%A5ndtering-av-pod-shutdown
=> implementerer koordinert shutdown av pod

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/arrangor/ArrangorService.kt, src/main/kotlin/no/nav/amt/deltaker/auth/AzureAdTokenClient.kt, src/main/kotlin/no/nav/amt/deltaker/auth/Exceptions.kt, src/main/kotlin/no/nav/amt/deltaker/auth/TilgangskontrollService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerHistorikkService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Deltaker.kt, src/main/kotlin/no/nav/amt/deltaker/external/api/VeilederApi.kt, src/main/kotlin/no/nav/amt/deltaker/isoppfolgingstilfelle/IsOppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/amt/deltaker/job/leaderelection/LeaderElection.kt, src/main/kotlin/no/nav/amt/deltaker/utils/StringUtils.kt, src/test/kotlin/no/nav/amt/deltaker/tiltakskoordinator/TiltakskoordinatorApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/utils/JWTUtils.kt, src/test/kotlin/no/nav/amt/deltaker/utils/TestEnvironmentUtils.kt
Kun reformatert filer med ktlint-feil vha. ktlint-plugin i IntelliJ.
=> Bumped ktlint rules til 1.6.0

build.gradle.kts, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApi.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandler.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandlerTest.kt
https://trello.com/c/pnoPOa9r/2308-ny-endring-for-felles-oppstart-n%C3%A5r-status-er-fullf%C3%B8rt-eller-avbrutt
=> Bump amtLib

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt, src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerStatusMedDeltakerId.kt, src/main/kotlin/no/nav/amt/deltaker/job/DeltakerProgresjon.kt, src/test/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepositoryTest.kt, src/test/kotlin/no/nav/amt/deltaker/job/DeltakerProgresjonTest.kt
https://trello.com/c/tHSEjqMf/2455-er-fullf%C3%B8rt-men-skal-v%C3%A6re-avbrutt
=> Håndterer fremtidige statuser for avbrutt, fullført og har sluttet
