src/main/kotlin/no/nav/amt/deltaker/Application.kt
src/main/kotlin/no/nav/amt/deltaker/application/plugins/Routing.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApi.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakerEndringResponse.kt
src/test/kotlin/no/nav/amt/deltaker/ApplicationTest.kt
src/test/kotlin/no/nav/amt/deltaker/application/plugins/AuthenticationTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/api/PameldingApiTest.kt

Siden jeg begynte å tenke på at vi kanskje må oppdatere statuser i noen av disse endringene så klarte jeg ikke å gi meg uten å se hvordan det ble seende ut å returnere en deltaker eller lignende etter endringene. Jeg skulle gjerne ønske at det holdt å få det på kafka, men jeg sitter å tviler på det hele tiden selv også. 
Jeg synes det er litt kjedelig å måtte hente ut full historikk ved vær endring, men jeg tror det er mer fremtidsrettet enn å bare returnere f.eks siste endring, for det kan fort bli til at en endring også fører med seg en vedtaksendring og da må man plutselig ha mer enn bare en ting uansett. Slik det er nå så returneres den samme informasjonen som deltaker-bffen bruker fra deltaker-v2.

Returner en DeltakerEndringResponse etter endring av deltaker

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/model/DeltakerEndring.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt

https://trello.com/c/RN6j61sF/1456-endre-api-for-%C3%A5-angi-oppstartsdato
Her kan vi sikkert også oppdatere statusen til har sluttet hvis man setter sluttdato tidligere enn i dag, men siden det er litt usannsynlig at man gjør det så tenker jeg vi kan la den automatiserte jobben håndtere det tilfellet (hvis de får en sluttdato tilbake i tid vil jo den sette avsluttende status).

endrer startdato-requesten så vi også kan angi sluttdato

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringService.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt
src/main/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringService.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepositoryTest.kt
src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt

https://trello.com/c/qM9z8wfO/1505-avslutt-deltakelse-skal-ikke-sette-harsluttet-hvis-ikke-sluttdato-er-passert

Harsluttet dato

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponse.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapper.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApiTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/api/model/DeltakelserResponseMapperTest.kt

https://trello.com/c/9fdET9es/1612-legge-til-id-for-gjennomf%C3%B8ring-i-respons-til-valp-api

legger til deltakerlisteid i apirespons

---

src/main/kotlin/no/nav/amt/deltaker/internal/InternalApi.kt

https://trello.com/c/dcZXckF0/1858-endre-internal-api-slik-at-vi-kan-endre-vilk%C3%A5rlig-status-til-ikke-aktuell

gjør ikke aktuell-api mer generelt

---

.github/workflows/deploy.yaml
build.gradle.kts
src/main/kotlin/no/nav/amt/deltaker/Application.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/forslag/kafka/ArrangorMeldingProducer.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerProducer.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerV1Producer.kt
src/main/kotlin/no/nav/amt/deltaker/hendelse/HendelseProducer.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/VedtakServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumerTest.kt
src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt

Hvis man stenger produseren etter hver sending så tar det fort 100ms per record sendt. Hvis man gjenbruker den så tar det kanskje 5-10ms per record. Siden vi ofte sender meldinger på flere topics for vær endring som skjer så medførte dette at responstiden ble veldig trege, en deltakerendring tar ofte mellom 500-700ms å utføre på `main` nå, med denne PRen så ligger de på rundt 250ms. 
Ved å ikke lukke produseren så risikerer man at ressurser lekker, men jeg tror ikke det er noe særlig farlig. Produserne våre som bruker fellesbiblioteket i dag stenges eller ikke og vi har ikke lagt merke til noe trøbbel der.

Bruk gjenbrukbar producer fra amt-lib

---

src/main/kotlin/no/nav/amt/deltaker/unleash/UnleashToggle.kt

https://trello.com/c/2jW2Jep2/1803-etter-lansering-endre-i-appene-som-sjekker-om-komet-er-master-for-deltakere-slik-at-komet-alltid-er-master-for-aft

endrer toggle så vi alltid er master for AFT

---

src/main/kotlin/no/nav/amt/deltaker/Application.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/HentDeltakelserApi.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumer.kt
src/main/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringService.kt
src/main/kotlin/no/nav/amt/deltaker/unleash/UnleashToggle.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/kafka/DeltakerConsumerTest.kt

https://trello.com/c/XOyqiyH6/1892-laste-arenadata-for-avklaring-arr-oppf%C3%B8lging-inn-i-verdikjeden

Støtte innlesing av nye tiltakstyper og at innlesingen kan skje før eksponering av data til valp

---

build.gradle.kts
src/main/kotlin/no/nav/amt/deltaker/Application.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandler.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringService.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorService.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandlerTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt

Når startdato endres, må deltakelsesmengdene også rekalkuleres for å sette riktig mengde i selve deltakerobjektet. Det er mye som skjer når man endrer startdato nå...
Det er litt kjipt å vedlikeholde den gjeldende deltakelsesmengden på deltakeren på denne måten. Det hadde nok vært lurt å refaktorere seg bort i fra å bruke de i det hele tatt, men det er en større jobb som krever at man håndterer kladd litt annerledes også er det litt kjedelig å måtte hente ut en liste med enten historikk eller deltakelsesmengder hver gang man skal ha en deltaker.

Endre deltakelsesmengde når startdato endres

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandler.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorServiceTest.kt

Dette sånn at Legg til oppstart endring på VTA kan ha null som sluttdato uten at det påvirker sluttdato på deltakelsen
(nå sendes sluttdato med i veileders flate, selv om sluttdato ikke er oppgitt av bruker)
https://trello.com/c/7c2mUSYU/2017-bug-vta-sender-med-sluttdato-n%C3%A5r-man-endrer-oppstartsdato-dersom-deltaker-har-sluttdato

Dersom sluttdato ikke er oppgitt i EndreOppstart endring så skal ikke deltakers sluttdato nullstilles

---

build.gradle.kts
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApi.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandler.kt
src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseType.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt

https://trello.com/c/pr6SFIj6/1968-muligheten-for-%C3%A5-nulle-ut-datoer-og-tilbakef%C3%B8re-brukeren-til-venter-p%C3%A5-oppstart-uten-datoer

støtte for å fjerne oppstartsdato

---

src/main/kotlin/no/nav/amt/deltaker/Application.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/DeltakerService.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandler.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringService.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerEndringServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/PameldingServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandlerTest.kt
src/test/kotlin/no/nav/amt/deltaker/job/DeltakerStatusOppdateringServiceTest.kt

En endring i ansvarsfordeling i koden i forsøk på å gjøre koden lettere å forstå.
Jeg brukte lang tid på å forstå koden sånn som den var så håper dette blir mer forståelig også for andre
* Metoden som "kalkulerte" de faktiske endringene på deltakerobjektet het DeltakerEndringHandler.handle() som førte til at jeg trodde at denne metoden faktisk insertet endringen i database, har derfor renamet funsjonen til sjekkUtfall() som vil returnere både endringstypen( FremtidigEndring, VellykketEndring osv ) og det resulterende deltakerobjektet som senere kan insertes.
* Tidligere var det DeltakerEndringService som hadde ansvar for å utlede endringer på deltakerobjektet. Det var her man "regnet ut"(via DeltakerEndringHandler) endringer på deltakeren som igjen ble returnert som "utfall" og resultatet …

Endrer ansvarsfordeling ved endring av deltakere for å gjøre koden mer lesbar

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringService.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandlerTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/endring/fra/arrangor/EndringFraArrangorServiceTest.kt

https://trello.com/c/L87U5g5O/2058-bug-g%C3%A5r-til-ikke-aktuell-n%C3%A5r-man-registrerer-periode-med-sluttdato-tilbake-i-tid

sluttdato i fortid skal gi har_sluttet

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/forslag/kafka/ArrangorMeldingConsumer.kt

Siden vi skriver vurderinger til topic for deltakere som vi ikke har i amt-deltaker ennå skal det ikke feile hvis man mottar en slik vurdering nå. Når vi tar over kurstiltakene bør nok dette endres.

skal ikke feile ved vurdering på deltaker som ikke finnes

---

src/main/kotlin/no/nav/amt/deltaker/hendelse/model/HendelseDeltaker.kt

https://trello.com/c/GBJo36Ae/2074-bytte-ut-gamle-arena-koder-for-tiltakstyper-med-nye-valp-koder-i-amt-distribusjon

sender med tiltakskode

---

src/main/kotlin/no/nav/amt/deltaker/tiltakskoordinator/TiltakskoordinatorApi.kt

Problemet er at amt-deltaker returnerer ikke historikk i det gamle endepunktet som fører til race condition når bff både upserter når man kaller del-med-arrangør og når man får record på topic

Lager ny versjon av del med arrangør for å rette problem med at historikk ikke blir populert riktig i bff

---

build.gradle.kts
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApi.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/api/model/EndringRequest.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/endring/DeltakerEndringHandler.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/DeltakerServiceTest.kt
src/test/kotlin/no/nav/amt/deltaker/deltaker/api/DeltakerApiTest.kt
src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt

* Nytt endepunkt for avbryt deltakelse som skal brukes når deltakelsen på felles oppstart ikke har blitt fullført
* Tilpasser avslutt deltakelse endepunkt for å fungere deltakere på felles oppstart
* Retter testdata sånn at man ikke får tilfeldige utfall på tiltakstype
https://trello.com/c/dmPgsl3w/2163-tiltaksarrang%C3%B8r-avslutte-deltakelse-modal-skal-man-angi-om-kurset-er-fullf%C3%B8rt-eller-ikke

Lager nytt endepunkt for avbrytelse av deltaker og tilpasser avslutt deltakelse for felles inntak

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/PameldingService.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/model/Deltaker.kt
src/main/kotlin/no/nav/amt/deltaker/deltakerliste/Deltakerliste.kt
src/main/kotlin/no/nav/amt/deltaker/deltakerliste/kafka/DeltakerlisteDto.kt
src/test/kotlin/no/nav/amt/deltaker/utils/data/TestData.kt

Relast er kjørt så oppstartstype vil ikke kunne være null, som ville kunne medføre rare feil med tolkning av oppstartstypen
https://trello.com/c/DoT0srVq/2231-oppstartstype-skal-ikke-v%C3%A6re-nullable-i-amt-deltaker

Oppstartstype skal ikke være nullable

---

build.gradle.kts

This PR includes the following Dependabot updates rebased into the bump-deps-20250708105322 branch:
- [Bump org.jlleitschuh.gradle.ktlint from 12.3.0 to 13.0.0](https://github.com/navikt/amt-deltaker/pull/477)
- [Bump io.getunleash:unleash-client-java from 11.0.1 to 11.0.2](https://github.com/navikt/amt-deltaker/pull/475)

Bump dependencies - 20250708105322

---

build.gradle.kts

This PR includes the following Dependabot updates rebased into the bump-deps-20250730110340 branch:
- [Bump io.ktor.plugin from 3.2.2 to 3.2.3](https://github.com/navikt/amt-deltaker/pull/510)
- [Bump ktorVersion from 3.2.2 to 3.2.3](https://github.com/navikt/amt-deltaker/pull/509)

Bump dependencies - 20250730110340

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/kafka/dto/DeltakerDto.kt

Arena trenger dato fra siste statusoppdatering hvis nyere enn deltaker sin endretDato for å kunne detektere endrede deltakere.

endretDato = maxOf(deltaker.status.opprettet, deltaker.sistEndret),

---

src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DbUtils.kt
src/main/kotlin/no/nav/amt/deltaker/deltaker/db/DeltakerRepository.kt

Denne PR-en forsøker å fikse at det kan være clock-skew mellom app og database, noe som medfører at select fra deltaker etter inserts i deltaker og deltaker_status feiler grunnet datobeskrankinger i get-spørring. 
Denne PR-en vil mest sannsynlig også fikse flaky tester.

Fix for clock-skew issues mellom app og database for deltaker_status-tabellen
